# Generated by Django 5.0.3 on 2024-04-01 17:09

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='add_class',
            field=models.CharField(blank=True, choices=[('abra_kadabra1', 'Абракадабра первая'), ('abra_kadabra2', 'x'), ('abra_kadabra3', 'x')], null=True),
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='board.cat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
